/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LoginNothingToSeeHereRouteImport } from './routes/login/nothing-to-see-here'
import { Route as LoginErrorRouteImport } from './routes/login/error'
import { Route as AuthenticatedSubmitRouteImport } from './routes/_authenticated/submit'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedQuoteIdRouteImport } from './routes/_authenticated/$quoteId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LoginNothingToSeeHereRoute = LoginNothingToSeeHereRouteImport.update({
  id: '/nothing-to-see-here',
  path: '/nothing-to-see-here',
  getParentRoute: () => LoginRoute,
} as any)
const LoginErrorRoute = LoginErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => LoginRoute,
} as any)
const AuthenticatedSubmitRoute = AuthenticatedSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuoteIdRoute = AuthenticatedQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/$quoteId': typeof AuthenticatedQuoteIdRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/search': typeof AuthenticatedSearchRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/login/error': typeof LoginErrorRoute
  '/login/nothing-to-see-here': typeof LoginNothingToSeeHereRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteWithChildren
  '/$quoteId': typeof AuthenticatedQuoteIdRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/search': typeof AuthenticatedSearchRoute
  '/submit': typeof AuthenticatedSubmitRoute
  '/login/error': typeof LoginErrorRoute
  '/login/nothing-to-see-here': typeof LoginNothingToSeeHereRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_authenticated/$quoteId': typeof AuthenticatedQuoteIdRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/submit': typeof AuthenticatedSubmitRoute
  '/login/error': typeof LoginErrorRoute
  '/login/nothing-to-see-here': typeof LoginNothingToSeeHereRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$quoteId'
    | '/admin'
    | '/search'
    | '/submit'
    | '/login/error'
    | '/login/nothing-to-see-here'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$quoteId'
    | '/admin'
    | '/search'
    | '/submit'
    | '/login/error'
    | '/login/nothing-to-see-here'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/$quoteId'
    | '/_authenticated/admin'
    | '/_authenticated/search'
    | '/_authenticated/submit'
    | '/login/error'
    | '/login/nothing-to-see-here'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/login/nothing-to-see-here': {
      id: '/login/nothing-to-see-here'
      path: '/nothing-to-see-here'
      fullPath: '/login/nothing-to-see-here'
      preLoaderRoute: typeof LoginNothingToSeeHereRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/error': {
      id: '/login/error'
      path: '/error'
      fullPath: '/login/error'
      preLoaderRoute: typeof LoginErrorRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authenticated/submit': {
      id: '/_authenticated/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof AuthenticatedSubmitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$quoteId': {
      id: '/_authenticated/$quoteId'
      path: '/$quoteId'
      fullPath: '/$quoteId'
      preLoaderRoute: typeof AuthenticatedQuoteIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedQuoteIdRoute: typeof AuthenticatedQuoteIdRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSubmitRoute: typeof AuthenticatedSubmitRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedQuoteIdRoute: AuthenticatedQuoteIdRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSubmitRoute: AuthenticatedSubmitRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginErrorRoute: typeof LoginErrorRoute
  LoginNothingToSeeHereRoute: typeof LoginNothingToSeeHereRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginErrorRoute: LoginErrorRoute,
  LoginNothingToSeeHereRoute: LoginNothingToSeeHereRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
